### ISSUE TITLE
Any plans for iOS

### ISSUE THREAD

**Issue by zsajjad** [glung/react-native-as-an-android-lib#1]
I am not an iOS developer but being React-Native developer i want similar thing for iOS is it possible to do that in iOS

**Comment by glung** [comment]
I dunno, sorry. But if you figure this out, let me know !

Am 21.12.2016 09:45 schrieb "Zain Sajjad" <notifications@github.com>:

I am not an iOS developer but being React-Native developer i want similar
thing for iOS is it possible to do that in iOS

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/glung/react-native-as-an-android-lib/issues/1>, or mute
the thread

**Comment by zsajjad** [comment]
Can you please describe the steps to run this project? I am unable to run it, multiple errors!

**Comment by glung** [comment]
In lib folder : <build with react>
In Application folder : `./gradlew assembleDebug`

Then you can install the APK.

**Comment by glung** [comment]
can you please with the steps as you would like it to be described?
https://github.com/glung/react-native-as-an-android-lib/blob/master/README.md

**Comment by zsajjad** [comment]
```
cd lib/
react-native-as-an-android-lib-master/lib : > npm i
react-native-as-an-android-lib-master/lib : > cd android/
react-native-as-an-android-lib-master/lib/android : > ./gradlew assembleDebug
```

I changed the `targetSdkVersion 23` & `buildToolsVersion "23.0.2"`
lib-debug.aar is there is output directory. Then,

`react-native-as-an-android-lib-master/Application : > ./gradlew assembleDebug`
```
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.facebook.react:react-native:0.32.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/facebook/react/react-native/0.32.0/react-native-0.32.0.pom
         https://jcenter.bintray.com/com/facebook/react/react-native/0.32.0/react-native-0.32.0.jar
         file:/home/fs/.m2/repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.pom
         file:/home/fs/.m2/repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.jar
         file:/media/fs/data/git/react-native-as-an-android-lib-master/lib/android/lib/build/outputs/aar/react-native-0.32.0.jar
         file:/media/fs/data/git/react-native-as-an-android-lib-master/lib/android/lib/build/outputs/aar/react-native.jar
         file:/data/android-sdk/extras/android/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.pom
         file:/data/android-sdk/extras/android/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.jar
         file:/data/android-sdk/extras/google/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.pom
         file:/data/android-sdk/extras/google/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.jar
         file:/data/android-sdk/extras/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.pom
         file:/data/android-sdk/extras/m2repository/com/facebook/react/react-native/0.32.0/react-native-0.32.0.jar
     Required by:
         Application:app:unspecified

```

**Comment by glung** [comment]
Maybe the react build tree changed. 

Locate the `aar` file and update the directory here : https://github.com/glung/react-native-as-an-android-lib/blob/master/Application/app/build.gradle#L34

Please, report here, and I'll fix it

**Comment by lolevsky** [comment]
For iOS you may want to check this one
https://github.com/artsy/emission

**Comment by deepCyan** [comment]
Hello, senior
Your project is of great significance to me.
I also wanna build my react-native project to a arr file.
So If you have time,would you mind telling me what should I do ? Like add or update some file...
Esteem it a favor

**Comment by glung** [comment]
Hello,

Thank you for your interest in my project. Though, it was an experiment a
while ago and it's not maintained.

If you come up with a new project, please do not hesitate to share it with
here.

Cheers

**Comment by waleedarshad** [comment]
+1

**Comment by kurroo10** [comment]
@glung Hello there, im interested with this kind of project, because right now, i want to integrating my React Native Apps (Which is already Done with some feature and working properly on APK/IPA) , but i want to made it like an AAR or .framework to re-useable on any other apps by importing it as Android Native Libs. where can i find something like tutorial , or maybe step by step the way you done this. bcs , its like for a week, nothing i can found

**Comment by glung** [comment]
Hey sorry, the repo is unmaintained (it's an experiment from 5 years ago) and now archived.
