### ISSUE TITLE
release lib

### ISSUE THREAD

**Issue by shukerullah** [glung/react-native-as-an-android-lib#2]
I am unable to build release variant. Here is my build.gradle

<pre>
buildTypes {
  release {
      minifyEnabled enableProguardInReleaseBuilds
      proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
      signingConfig signingConfigs.release
  }
}

**Comment by glung** [comment]
Hey sorry, the repo is unmaintained and now archived.
