### ISSUE TITLE
Failed to resolve: com.facebook.react:react-native:0.32.0

### ISSUE THREAD

**Issue by pushpendra-choudhary** [glung/react-native-as-an-android-lib#4]
Hey I am trying integrate my react native aar file with android project and I am facing following issue in my gradle file.

> Failed to resolve: com.facebook.react:react-native:0.32.0

It's working fine with react-native android project but not for android java project. Do you have any idea?

**Comment by glung** [comment]
sorry I don't know. This is just an exploration I did some time last year and I am not working on it anymore.
